# Generated by Django 4.2.25 on 2025-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('guestsc', models.ImageField(upload_to='')),
                ('guestsv', models.IntegerField()),
                ('guestsn', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
